sandwichr/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "static#index"

  resources :sandwiches, only: [:index, :show], controller: "sandwich_views"

  scope :api do
    resources :ingredients, only: [:create, :destroy, :show]
    resources :sandwiches, except: [:new, :edit]

    post "/sandwiches/:id/ingredients/add", to: "sandwiches#add_ingredient"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sandwichr/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sandwichr/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :sandwich_ingredients
  has_many :sandwiches, through: "sandwich_ingredients"
end

sandwichr/app/models/sandwich.rb
class Sandwich < ApplicationRecord
  has_many :sandwich_ingredients
  has_many :ingredients, through: "sandwich_ingredients"
end

sandwichr/app/models/sandwich_ingredient.rb
class SandwichIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :sandwich
end

sandwichr/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

sandwichr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :add_extra_params, if: :devise_controller?

  protected

  def add_extra_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

sandwichr/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def create
    the_ingredient = Ingredient.create(ingredient_params)
    render json: the_ingredient
  end

  def show
    the_ingredient = Ingredient.find_by(id: params[:id])

    if the_ingredient
      render json: the_ingredient
    else
      render status: 404, json: { error: "Ingredient #{params[:id]} not found" }
    end
  end

  def destroy
    the_ingredient = Ingredient.find_by(id: params[:id])

    if the_ingredient
      the_ingredient.destroy
      head :no_content
    else
      render status: 404, json: { error: "Ingredient #{params[:id]} not found" }
    end
  end


  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :calories)
  end

end

sandwichr/app/controllers/sandwich_views_controller.rb
class SandwichViewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @sandwiches_array = Sandwich.all
    render :index
  end

  def show
    @the_sandwich = Sandwich.find(params[:id])
    @all_ingredients = Ingredient.all

    render :show
  end

end

sandwichr/app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController

  def index
    sandwiches_array = Sandwich.all
    render json: sandwiches_array
  end

  def create
    the_sandwich = Sandwich.create(sandwich_params)
    render json: the_sandwich
  end

  def show
    the_sandwich = Sandwich.find_by(id: params[:id])

    if the_sandwich
      # render json: { sandwich: the_sandwich, ingredients: the_sandwich.ingredients }
      render json: the_sandwich.to_json(include: [:ingredients])
    else
      render status: 404, json: { error: "Sandwich #{params[:id]} not found" }
    end
  end

  def update
    the_sandwich = Sandwich.find_by(id: params[:id])

    if the_sandwich
      the_sandwich.update(sandwich_params)
      render json: the_sandwich
    else
      render status: 404, json: { error: "Sandwich #{params[:id]} not found" }
    end
  end

  def destroy
    the_sandwich = Sandwich.find_by(id: params[:id])

    if the_sandwich
      the_sandwich.destroy
      head :no_content
    else
      render status: 404, json: { error: "Sandwich #{params[:id]} not found" }
    end
  end

  # post "/sandwiches/:id/ingredients/add"
  def add_ingredient
    # SandwichIngredients.create(sandwich_id: param[:id], ingredient_id: params[:ingredient_id])

    the_sandwich = Sandwich.find_by(id: params[:id])
    the_ingredient = Ingredient.find_by(id: params[:ingredient_id])

    if the_sandwich && the_ingredient
      the_sandwich.ingredients.push( the_ingredient )

      render json: the_sandwich.to_json(include: [:ingredients])
    else
      render status: 404, json: { error: "Sandwich #{params[:id]} not found" }
    end
  end


  private

  def sandwich_params
    params.require(:sandwich).permit(:name, :bread_type)
  end

end

sandwichr/app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
    render :index
  end

end

sandwichr/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

sandwichr/app/helpers/sandwich_views_helper.rb
module SandwichViewsHelper
end

sandwichr/app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

sandwichr/app/helpers/static_helper.rb
module StaticHelper
end

sandwichr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sandwichr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>
      <a href="/"> Sandwichr </a>
    </h1>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <p> Made with &hearts; at Ironhack. </p>
  </body>
</html>

sandwichr/app/views/sandwich_views/index.html.erb
<h2> List of sandwiches </h2>

<ul>
  <% @sandwiches_array.each do |the_sandwich| %>
    <li>
      <a href="<%= sandwich_path(the_sandwich) %>">
        <%= the_sandwich.name %>
      </a>
    </li>
  <% end %>
</ul>

sandwichr/app/views/sandwich_views/show.html.erb
<h2> Sandwich details </h2>

<h3 class="js-sandwich-id" data-sandwich-id="<%= @the_sandwich.id %>">
  <%= @the_sandwich.name %>
</h3>

<p>
  Bread type:
  <strong> <%= @the_sandwich.bread_type %> </strong>
</p>

<h4> Current ingredients </h4>

<ul class="js-current-ingredients">
  <% @the_sandwich.ingredients.each do |the_ingredient| %>
    <li> <%= the_ingredient.name %> </li>
  <% end %>
</ul>


<h4> Add more ingredients </h4>

<% @all_ingredients.each do |one_ingredient| %>
  <li>
    <button class="js-add-ingredient"
        data-ingredient-id="<%= one_ingredient.id %>">
      <%= one_ingredient.name %> </li>
    </button>
  </li>
<% end %>